### ISSUE TITLE
Not an error, but an annoying warning

### ISSUE THREAD

**Issue by BachoSeven** [wis/mpvSockets#5]
Hi, I have not been able to figure out why, but using this script gives me the following whenever I use `mpv`:
``` sh
Cannot find main.* for any supported scripting backend in: /home/fra/.config/mpv/scripts/mpvSockets
```
Of course I can hide the warning by using something like `--really-quiet`, but do you have any idea why it shows up in the first place?

**Comment by samuccagomes** [comment]
I'm having the same problem here

**Comment by wis** [comment]
> do you have any idea why it shows up in the first place?

The error message is cryptic but I figured out it is caused by mpv trying to read and parse everything in the scripts directory as script files and failing to do so for the mpvSockets directory inside it.

You should move any directories out of the scripts directory, [here's the updated method](https://github.com/LukeSmithxyz/voidrice/tree/f1814b3690d61cc122c83381ed013eaf20a33971/.config/mpv) for loading modules/plugins while keeping them inside their git clone directories mpvSockets, copy or update modules.lua to the scripts directory and clone mpvSockets to a directory named script_modules inside mpv's config directory.
